### ISSUE TITLE
Netlify build is failing with chrome-aws-lambda v10

### ISSUE THREAD

**Issue by pixelastic** [pixelastic/api.pixelastic.com#13]
Seems like since I upgraded from v9 to v10, I'm now over the limit allowed by AWS. This is a bummer because there isn't much I can do. AWS has a limit at 50M, and the zip of chrome-aws-lambda is already at 53 with v10.

**Comment by pixelastic** [comment]
This has been fixed by setting the following code in `netlify.toml`:

```toml
  node_bundler = "esbuild"
  external_node_modules = ["chrome-aws-lambda"]
```
